### ISSUE TITLE
Example usages for GRAM5 are missing params in code block

### ISSUE THREAD

**Issue by iWangJiaxiang** [gridcf/gct-docs#15]
Please visit [https://gridcf.org/gct-docs/latest/gram5/user/index.html#_running_basic_jobs_with_strong_code_globus_job_run_code_strong](https://gridcf.org/gct-docs/latest/gram5/user/index.html#_running_basic_jobs_with_strong_code_globus_job_run_code_strong) and you could see the code blocks for example are not complete.

![image](https://user-images.githubusercontent.com/19409802/61351241-aea62780-a89c-11e9-8f7e-8e4d9f6d0e9a.png)

No params so the examples are not useful at all

**Comment by fscheiner** [comment]
Closed with PR #16.
